### ISSUE TITLE
How to add model.query like Flask-Sqlalchemy's one or Flask-Alchy's one ?

### ISSUE THREAD

**Issue by museghost** [dgilland/sqlservice#10]
Hi, I am a fan of this project since Alchy and Flask Alchy.

Now, I am developing a flask program with Flask-Security, based on this project sqlservice.

When trying a test, I found a problem as below.

```python
  File "/home/user1/test/lib/python3.5/site-packages/flask_security/datastore.py", line 206, in find_role
    return self.role_model.query.filter_by(name=role).first()
AttributeError: type object 'Role' has no attribute 'query'
```

I assume that this problem is caused by the absent of "query" attribute in Model from sqlservice.
Yeah, in Flask-Sqlalchemy, they put query and its method in the basic model, and the Flask-Alchy did so, however, sqlservice does not support it until now.

Another tragic for me, since I am newbie of developing the Flask extentions, it is very hard to add such feature into the new sqlservice.

So, if possible, could you please provide any proof code or patch for solving this issue ?

Best Regards
Thanks

**Comment by dgilland** [comment]
I've been somewhat reluctant to implement the query property feature from alchy/Flask-SQLAlchemy in sqlservice.

You can actually get the same functionality as the query property using the SQLClient object itself:

```python
from sqlservice import SQLClient

from .models import Model

db = SQLClient(model_class=Model)

db.Role.filter_by(name=role).first()

# The above is the same as...
db.query(Role).filter_by(name=role).first()
```

The only limitation when compared to alchy's query property is that `db.<Model>` doesn't support custom query classes per model via the `<Model>.query_class` attribute.

I chose to implement the above instead of the query property b/c when you add the query property to a model class you are binding `Model.query` to the database session of `db`. I wanted to avoid that kind of coupling between models and the database session so that the models would be agnostic towards the session and not bound to any particular session if the user is using the same model classes across different sessions.

However, with that being said, implementing a query property on model classes is doable:

```python
from sqlalchemy import orm
from sqlservice import SQLClient

from .models import Model

class QueryProperty(object):
    def __init__(self, session, default_query_class):
        self.session = session
        self.default_query_class = default_query_class

    def __get__(self, model_instance, model_class):
        mapper = orm.class_mapper(model_class)

        if not mapper:
            return

        query_class = getattr(model_class, 'query_class', self.default_query_class)
        query_property = query_class(mapper, session=self.session)

        return query_property

class MySQLClient(SQLClient):
    def __init__(self, *args, **kargs):
        super().__init__(*args, **kargs)

        self.extend_model_with_query_property()

    def extend_model_with_query_property(self):
        self.model_class.query = QueryProperty(self.session, self.query_class)

db = MySQLClient(model_class=Model)
Role.query.filter_by(name=name).first()
```

NOTE: This is untested so there may be some issues with it. I've basically modified the `QueryProperty` class from [alchy.query.QueryProperty](https://github.com/dgilland/alchy/blob/f3d9a626da56c2b517576e8d18fb8a0bdba71e2a/alchy/query.py#L448) to better integrate with sqlservice but the implementation is roughly the same.
