### ISSUE TITLE
Unable to declare class_registry, or sqlalchemy library incompatibility?

### ISSUE THREAD

**Issue by daviddpark** [dgilland/sqlservice#14]
Awesome library! Thank you so much for the work that you've done here.

I can't figure out how to get sqlalchemy_continuum and sqlservice to play nicely together.

Here is some example code to reproduce the problem:

```
# model.py
# Assumes requirements met:
# SQLAlchemy-Continuum==1.3.1
# sqlservice==0.13.0

from sqlalchemy import (Column, ForeignKey, func, types)
from sqlalchemy.orm import relationship, configure_mappers
from sqlservice import ModelBase, SQLClient, declarative_base


# To use continuum, call make_versioned before declaring models
from sqlalchemy_continuum.plugins import TransactionMetaPlugin
from sqlalchemy_continuum import make_versioned
meta_plugin = TransactionMetaPlugin()
make_versioned(user_cls=None, plugins=[meta_plugin])

class_registry = {}


@declarative_base  # Possible solution:  @declarative_base(class_registry=class_registry)
class Model(ModelBase):
    pass


class User(Model):
    __versioned__ = {}
    __tablename__ = 'user'

    id = Column(types.Integer, primary_key=True)
    name = Column(types.Unicode(30))
    things = relationship('Thing', backref='user', cascade='all, delete-orphan')


class Thing(Model):
    __versioned__ = {}
    __tablename__ = 'thing'

    id = Column(types.Integer, primary_key=True)
    description = Column(types.Unicode(50))
    user_id = Column(
        types.Integer, ForeignKey('user.id', onupdate="CASCADE", ondelete="CASCADE")
    )

db = SQLClient({'SQL_DATABASE_URI': 'sqlite://'}, model_class=Model)

configure_mappers()
```

When executing this code, you should see:
```
$ python model.py
Traceback (most recent call last):
  File "model.py", line 50, in <module>
    configure_mappers()
  File "/Users/ddp/.pyenv/versions/continuum_sqlservice/lib/python3.5/site-packages/sqlalchemy/orm/mapper.py", line 2887, in configure_mappers
    Mapper.dispatch._for_class(Mapper).after_configured()
  File "/Users/ddp/.pyenv/versions/continuum_sqlservice/lib/python3.5/site-packages/sqlalchemy/event/attr.py", line 218, in __call__
    fn(*args, **kw)
  File "/Users/ddp/.pyenv/versions/continuum_sqlservice/lib/python3.5/site-packages/sqlalchemy/orm/events.py", line 616, in wrap
    fn(*arg, **kw)
  File "/Users/ddp/.pyenv/versions/continuum_sqlservice/lib/python3.5/site-packages/sqlalchemy_continuum/builder.py", line 161, in configure_versioned_classes
    self.build_transaction_class()
  File "/Users/ddp/.pyenv/versions/continuum_sqlservice/lib/python3.5/site-packages/sqlalchemy_continuum/builder.py", line 141, in build_transaction_class
    self.manager.create_transaction_model()
  File "/Users/ddp/.pyenv/versions/continuum_sqlservice/lib/python3.5/site-packages/sqlalchemy_continuum/manager.py", line 158, in create_transaction_model
    self.transaction_cls = self.transaction_cls(self)
  File "/Users/ddp/.pyenv/versions/continuum_sqlservice/lib/python3.5/site-packages/sqlalchemy_continuum/factory.py", line 9, in __call__
    registry = manager.declarative_base._decl_class_registry
AttributeError: type object 'ModelBase' has no attribute '_decl_class_registry'
```

It is likely that this "problem" is not really an issue and is in fact due to my inexperience with SQLAlchemy in general, but I see that SQLAlchemy's declarative_base function accepts a class_registry parameter. I shall follow up this issue with a pull request containing a potential fix, but if I have misdiagnosed the problem and you see another solution that involves configuration or subclassing rather than a code change, I would prefer that to imposing change on your library.

**Comment by dgilland** [comment]
The issue is due to the existence of `ModelBase.metadata = None` in [sqlservice/model.py#L44](https://github.com/dgilland/sqlservice/blob/ac0dad2bfea9b65c01013120feba06fe4ec06068/sqlservice/model.py#L44) which causes [sqlalchemy_utils/functions/orm.py:get_declarative_base](https://github.com/kvesteri/sqlalchemy-utils/blob/40fd44c2bb38a2b0e2c007895483a88a4ecc336c/sqlalchemy_utils/functions/orm.py#L761) (used in [sqlalchemy_continuum/builder.py](https://github.com/kvesteri/sqlalchemy-continuum/blob/ee857beaad6c5ea113fcda31a35c4e11116e70d7/sqlalchemy_continuum/builder.py#L140)) to return the wrong class. The problem is that it sees a `metadata` attribute on `ModelBase` and goes "up" to the next base class which is `object` (i.e. instead of stopping at `ModelBase` it  goes too far and returns `object` which later causes the `has no attribute '_decl_class_registry'` error you received).

The short-term workaround would be to delete the `ModelBase.metadata` attribute as in:

```python
del ModelBase.metadata

@declarative_base
class Model(ModelBase):
    pass
```

Obviously not ideal but it "works" for this case.

Long-term, I need to decide whether to either maintain the status-quo or rename/drop `ModelBase.metadata` (along with `ModelBase.metaclass`) so that there is no conflict (likely a rename). I may lean towards a single "config" class attribute to lessen the impact of this kind of thing and to reduce the special class attributes defined in `ModelBase` (currently there's `ModelBase.metadata`, `metaclass`, and `__dict_args__` so may move all those under a single class attribute instead).

**Comment by daviddpark** [comment]
Thank you for your prompt response, Derrick. This workaround enables me to continue working with your library, so thank you for your thoughtful response.

**Comment by dgilland** [comment]
FYI, I've removed `ModelBase.metadata` and `ModelBase.metaclass` class attributes in the latest release, [v0.14.0](https://pypi.python.org/pypi/sqlservice/0.14.0). There's also a fix to the decorator usage of `declarative_base` which was basically broken to begin with when used as a decorator (it just happened to work as a decorator when called with no args). There's a new `@as_declarative` decorator which correctly implements the declarative decorator functionality.

**Comment by daviddpark** [comment]
Thank you so much for the heads up on this, Derrick.
