### ISSUE TITLE
Support SQLAlchemy 1.4+

### ISSUE THREAD

**Issue by dsully** [dgilland/sqlservice#30]
Getting this in for tracking.

**Comment by dgilland** [comment]
I've fixed the SQLAlchemy 1.4 compatibility issues locally and will be releasing them soon. Fortunately, most of the issues were related to testing and not an issue with the library itself. However, there were a few incompatibilities that cannot be resolved:

- `sqlservice.Query.entities` - Underlying class in SQLAlchemy was removed/replaced with different implementation.
- `sqlservice.Query.join_entities` - Same as `sqlservice.Query.entities`.
- `sqlservice.Query.all_entities` - Same as `sqlservice.Query.entities`.
- `sqlservice.SQLClient.prune` - The underlying `session.prune` method was previously deprecated in SQLAlchemy and removed in 1.4.

Looking ahead to SQLAlchemy 2.0 compatibility, I'm planning a larger overhaul of `sqlservice` to conform to the SQLAlchemy 2.0 style of engine/session/orm usage. Many of the features in `sqlservice` are based on "legacy" SQLAlchemy patterns so there will be a lot of breaking changes, but I think most of the features can be adapted to the new style.

But since the next major release of `sqlservice` will be backwards-incompatible, there's an opportunity to reconsider existing implementations/features. If you have any suggestions for the `sqlservice 2.0` release, I'd love to hear them.

**Comment by dsully** [comment]
Good to hear.

From a cursory look at the new `SQLAlchemy` features, it feels like some amount of the existing code in `sqlservice` could be removed even.

I'll think about any features for 2.0 - but for the most part what exists today just works.

I'd include type hinting on any future work however.

**Comment by dgilland** [comment]
I've released [1.3.0](https://pypi.org/project/sqlservice/1.3.0/) which includes some minor compatibility fixes so that sqlservice will work with SQLAlchemy 1.4 in pre-2.0 mode. The 2.0 mode (i.e. creating SQLAlchemy engine and session using the `future=True` flag) is untested so it may or may not work.

I've started work on the sqlservice 2.0 overhaul that will be SQLAlchemy 1.4+ only with a `future=True`-only implementation for engine and session objects.

**Comment by dgilland** [comment]
sqlservice 2.0 has been release: https://pypi.org/project/sqlservice/2.0.0/

It's a major rewrite that conforms to the SQLAlchemy 1.4-future/2.0 style. Lots of backwards incompatibilities though so be prepared. There is a sqlserivce 2.0 migration guide in the docs to help, though.
