### ISSUE TITLE
Migration from v1 - how to handle scopefunc?

### ISSUE THREAD

**Issue by f3flight** [dgilland/sqlservice#40]
Hello @dgilland! I'm migrating an internal project to sqlservice v2, and I ran into an issue - our impl in v1 uses "scopefunc" inside session_options. This worked with sqlservice v1 becase it used a custom "create_session" function where it would pop this parameter, create a sessionmaker, and create a scoped_session, passing in scopefunc. In v2 there is no handling for scopefunc anymore. Can you help me understand how I can replicate the behavior of v1 with scopefunc when using v2?

**Comment by dgilland** [comment]
Part of the migration to v2 was to make sessions more explicit where sessions are begun and committed within the local scope of the db transaction and where sessions are passed as arguments instead of implicitly getting a session from a registry. This change was done to better align with the SQLAlchemy 2.0 style of sessions (https://docs.sqlalchemy.org/en/20/changelog/migration_20.html).

But if you want to use a scopefunc, then the easiest thing to do would be to sublcass `Database` and override the `session()` method: https://github.com/dgilland/sqlservice/blob/a2dc879a3197955245cdfec8fc112e726bce2c3b/src/sqlservice/database.py#L167-L179

So something like this (untested):

```python
import typing as t

from sqlalchemy import Session
from sqlalchemy.orm import scoped_session
import sqlservice

class Database(sqlservice.Database):
    def session(self, **kwargs: t.Any) -> Session:
        # NOTE: Could do this in "__init__()" or some other method instead.
        if getattr(self, "_session", None) is None:
            self._session = scoped_session(self.sessionmaker, scopefunc=self.session_options.get("scopefunc"))
        return self._session(**kwargs)
```

**Comment by f3flight** [comment]
Thanks for this guidance @dgilland !
